// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: batches.sql

package db

import (
	"context"
)

const createBatch = `-- name: CreateBatch :one
INSERT INTO batches(total_files, status)
  VALUES ($1, $2)
RETURNING
  id, total_files, processed_files, failed_count, total_original_size, total_optimized_size, status, duration_seconds, compression_ratio, created_at, updated_at
`

type CreateBatchParams struct {
	TotalFiles int32
	Status     string
}

func (q *Queries) CreateBatch(ctx context.Context, arg CreateBatchParams) (Batch, error) {
	row := q.db.QueryRow(ctx, createBatch, arg.TotalFiles, arg.Status)
	var i Batch
	err := row.Scan(
		&i.ID,
		&i.TotalFiles,
		&i.ProcessedFiles,
		&i.FailedCount,
		&i.TotalOriginalSize,
		&i.TotalOptimizedSize,
		&i.Status,
		&i.DurationSeconds,
		&i.CompressionRatio,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBatch = `-- name: GetBatch :one
SELECT
  id, total_files, processed_files, failed_count, total_original_size, total_optimized_size, status, duration_seconds, compression_ratio, created_at, updated_at
FROM
  batches
WHERE
  id = $1
`

func (q *Queries) GetBatch(ctx context.Context, id int32) (Batch, error) {
	row := q.db.QueryRow(ctx, getBatch, id)
	var i Batch
	err := row.Scan(
		&i.ID,
		&i.TotalFiles,
		&i.ProcessedFiles,
		&i.FailedCount,
		&i.TotalOriginalSize,
		&i.TotalOptimizedSize,
		&i.Status,
		&i.DurationSeconds,
		&i.CompressionRatio,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateBatchProgress = `-- name: UpdateBatchProgress :exec
UPDATE
  batches
SET
  processed_files = $1,
  total_original_size = $2,
  total_optimized_size = $3,
  updated_at = NOW()
WHERE
  id = $4
`

type UpdateBatchProgressParams struct {
	ProcessedFiles     int32
	TotalOriginalSize  int64
	TotalOptimizedSize int64
	ID                 int32
}

func (q *Queries) UpdateBatchProgress(ctx context.Context, arg UpdateBatchProgressParams) error {
	_, err := q.db.Exec(ctx, updateBatchProgress,
		arg.ProcessedFiles,
		arg.TotalOriginalSize,
		arg.TotalOptimizedSize,
		arg.ID,
	)
	return err
}

const updateBatchStatus = `-- name: UpdateBatchStatus :exec
UPDATE
  batches
SET
  status = $1,
  updated_at = NOW()
WHERE
  id = $2
`

type UpdateBatchStatusParams struct {
	Status string
	ID     int32
}

func (q *Queries) UpdateBatchStatus(ctx context.Context, arg UpdateBatchStatusParams) error {
	_, err := q.db.Exec(ctx, updateBatchStatus, arg.Status, arg.ID)
	return err
}
