// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Batch struct {
	ID                 int32
	TotalFiles         int32
	ProcessedFiles     int32
	FailedCount        int32
	TotalOriginalSize  int64
	TotalOptimizedSize int64
	Status             string
	DurationSeconds    pgtype.Int4
	CompressionRatio   pgtype.Float8
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
}

type Video struct {
	ID                int32
	BatchID           int32
	OriginalFilename  string
	OptimizedFilename pgtype.Text
	OriginalSize      int64
	OptimizedSize     pgtype.Int8
	Status            string
	ErrorMessage      pgtype.Text
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}
