// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
)

const getVideo = `-- name: GetVideo :one
SELECT id, batch_id, original_filename, optimized_filename, original_size, optimized_size, status, error_message, created_at, updated_at FROM videos
WHERE id = $1
`

func (q *Queries) GetVideo(ctx context.Context, id int32) (Video, error) {
	row := q.db.QueryRow(ctx, getVideo, id)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.BatchID,
		&i.OriginalFilename,
		&i.OptimizedFilename,
		&i.OriginalSize,
		&i.OptimizedSize,
		&i.Status,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
