// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: videos.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createVideo = `-- name: CreateVideo :one
INSERT INTO videos(batch_id, original_filename, original_size, status)
  VALUES ($1, $2, $3, $4)
RETURNING
  id, batch_id, original_filename, optimized_filename, original_size, optimized_size, status, error_message, created_at, updated_at
`

type CreateVideoParams struct {
	BatchID          int32
	OriginalFilename string
	OriginalSize     int64
	Status           string
}

func (q *Queries) CreateVideo(ctx context.Context, arg CreateVideoParams) (Video, error) {
	row := q.db.QueryRow(ctx, createVideo,
		arg.BatchID,
		arg.OriginalFilename,
		arg.OriginalSize,
		arg.Status,
	)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.BatchID,
		&i.OriginalFilename,
		&i.OptimizedFilename,
		&i.OriginalSize,
		&i.OptimizedSize,
		&i.Status,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVideo = `-- name: GetVideo :one
SELECT
  id, batch_id, original_filename, optimized_filename, original_size, optimized_size, status, error_message, created_at, updated_at
FROM
  videos
WHERE
  id = $1
`

func (q *Queries) GetVideo(ctx context.Context, id int32) (Video, error) {
	row := q.db.QueryRow(ctx, getVideo, id)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.BatchID,
		&i.OriginalFilename,
		&i.OptimizedFilename,
		&i.OriginalSize,
		&i.OptimizedSize,
		&i.Status,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVideosByBatch = `-- name: GetVideosByBatch :many
SELECT
  id, batch_id, original_filename, optimized_filename, original_size, optimized_size, status, error_message, created_at, updated_at
FROM
  videos
WHERE
  batch_id = $1
`

func (q *Queries) GetVideosByBatch(ctx context.Context, batchID int32) ([]Video, error) {
	rows, err := q.db.Query(ctx, getVideosByBatch, batchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Video
	for rows.Next() {
		var i Video
		if err := rows.Scan(
			&i.ID,
			&i.BatchID,
			&i.OriginalFilename,
			&i.OptimizedFilename,
			&i.OriginalSize,
			&i.OptimizedSize,
			&i.Status,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateVideoSizes = `-- name: UpdateVideoSizes :exec
UPDATE
  videos
SET
  optimized_filename = $1,
  optimized_size = $2,
  status = $3,
  updated_at = NOW()
WHERE
  id = $4
`

type UpdateVideoSizesParams struct {
	OptimizedFilename pgtype.Text
	OptimizedSize     pgtype.Int8
	Status            string
	ID                int32
}

func (q *Queries) UpdateVideoSizes(ctx context.Context, arg UpdateVideoSizesParams) error {
	_, err := q.db.Exec(ctx, updateVideoSizes,
		arg.OptimizedFilename,
		arg.OptimizedSize,
		arg.Status,
		arg.ID,
	)
	return err
}

const updateVideoStatus = `-- name: UpdateVideoStatus :exec
UPDATE
  videos
SET
  status = $1,
  error_message = $2,
  updated_at = NOW()
WHERE
  id = $3
`

type UpdateVideoStatusParams struct {
	Status       string
	ErrorMessage pgtype.Text
	ID           int32
}

func (q *Queries) UpdateVideoStatus(ctx context.Context, arg UpdateVideoStatusParams) error {
	_, err := q.db.Exec(ctx, updateVideoStatus, arg.Status, arg.ErrorMessage, arg.ID)
	return err
}
